version: '3.8'

services:
  web:
    image: binit13/model-a3:v1
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8501
    ports:
      - "4000:8501"
    restart: always

