name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs this pipeline whenever code is pushed to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t binit13/model-a3:latest .
          docker tag binit13/model-a3:latest binit13/model-a3:${{ github.run_number }}
          docker push binit13/model-a3:latest
          docker push binit13/model-a3:${{ github.run_number }}

#      - name: SSH into ml2023 and Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.ML2023_HOST }}
#          username: ${{ secrets.ML2023_USER }}
#          password: ${{ secrets.ML2023_PASSWORD }}
#          script: |
#            cd ~/deployment-folder
#            docker-compose down
#            docker pull binit13/model-a2:latest
#            docker-compose up -d