name: Build, Test, and Deploy Model

on:
  push:
    branches:
      - main  # Runs this pipeline whenever code is pushed to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Set up MLflow Authentication
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

      - name: Run Model Tests
        run: |
          pytest ProjectA3/test_model.py  # Adjust path if needed

      # 🚀 COMMENTED OUT DOCKER BUILD & PUSH TEMPORARILY
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and Push Docker Image
      #   run: |
      #     docker build -t binit13/model-a3:latest .
      #     docker tag binit13/model-a3:latest binit13/model-a3:${{ github.run_number }}
      #     docker push binit13/model-a3:latest
      #     docker push binit13/model-a3:${{ github.run_number }}

  transition-to-production:
    needs: build-and-test  # ✅ KEEP THIS LINE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up MLflow Authentication
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

      - name: Transition Best Model to Production
        run: |
          python ProjectA3/transition.py

  deploy:
    needs: transition-to-production  # Deploys only if transition was successful
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into ML2023 and Deploy
        run: |
          ssh ml2023 << 'EOF'
            cd ~/st124783
            docker compose -f docker-compose-deploy.yaml down
            docker pull binit13/model-a3:latest
            docker compose -f docker-compose-deploy.yaml up -d
          EOF